version: "3.7"

services:

  # mongo:
  #   image: mongo:4.2
  #   hostname: mongo
  #   container_name: mongo
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_DATABASE: miniautorizador
  #     MONGO_INITDB_ROOT_USERNAME: user
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - ./scripts/init.js:/docker-entrypoint-initdb.d/init.js:ro

  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: miniautorizador
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      
  mongo:
    image: mongo
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - "27017:27017"
# acesso administrativo MongoDB:
#   http://0.0.0.0:8081
  mongo-express:
    image: mongo-express
    links:
      - mongo
    container_name: "mongo-express"
    ports:
      - 8081:8081
      
# acesso administrativo RabbitMQ:
#   http://0.0.0.0:8082
#    user: guest
#    pass: guest      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./rabbitmq-data/:/var/lib/rabbitmq/
    ports:
      - 5672:5672
      - 8082:15672